[package]
name = "lattice-qcd-rs"
version = "0.1.0"
authors = [" Aliénore Bouttefeux <alienore.bouttefeux@gmail.com>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/ABouttefeux/lattice-qcd-rs"
categories = ["science"]
description  = "Lattice QCD"
keywords  = ["QCD", "Lattice"]
publish = false

[features]
serde-serialize = ["serde"]
default = ["serde-serialize"]

[workspace]
members = ["simulation-bin"]

[dependencies]
nalgebra = { version = "0.24.0", features = ["serde-serialize"] }
once_cell = "1.5.2"
approx = "0.4.0"
num-traits = "0.2.14"
rand = "0.8.2"
rand_distr = "0.4.0"
crossbeam = "0.8.0"
rayon = "1.5.0"
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench"
harness = false

[profile.test]
opt-level = 2 # in order to have resonable test time


[profile.release]
codegen-units = 1
lto = true
