format_code_in_doc_comments = true
normalize_comments = false
reorder_impl_items = false
group_imports = "StdExternalCrate"
unstable_features = true
use_field_init_shorthand = true
wrap_comments = false
control_brace_style = "AlwaysSameLine"
