format_code_in_doc_comments = true
normalize_comments = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
unstable_features = true
use_field_init_shorthand = true
wrap_comments = false
control_brace_style = "ClosingNextLine"
