name: Benches

on:
  push:
    branches: [ main, develop ]


env:
  CARGO_TERM_COLOR: always

jobs:
  bench:
    name: Run benches for Lattice QCD rs
    runs-on: ubuntu-latest
    # env:
    #   CRITERION_TOKEN: ${{ secrets.CRITERION_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run benchmarks
        run: |
          # run benchmarks and save baseline in a directory called "new"
          cargo bench
      # - name: Upload benchmarks
      #   run: |
      #     # upload the files
      #     bash <(curl -s https://criterion.dev/bash)
