name: clippy check

on:
  workflow_call:
    inputs:
      features_flag: 
        description: 'feature flag used on the cargo command'
        required: false
        default: '--all-features'
        type: string
      toolchain:
        description: 'rust toolchain'
        required: false
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  linter:
    name: lint code with clippy on nightly
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install Rust nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ inputs.toolchain }}
        components: cargo, clippy
        default: true
    
    - name: Linter
      run: cargo clippy --all --verbose --all-targets ${{ inputs.features_flag }} -- --no-deps --deny warnings
    
    - name: Linter release
      run: cargo clippy --all --verbose --all-targets --release ${{ inputs.features_flag }} -- --no-deps --deny warnings
