name: coverage

env:
  CARGO_TERM_COLOR: always

on:
  workflow_call:
      inputs:
        profile_file_name_prefix:
          description: 'prefix of the LLVM profile file'
          required: true
          default: 'profile'
          type: string
        features_flag: 
          description: 'feature flag used on the cargo command'
          required: true
          default: '--all-features'
          type: string

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: llvm-tools-preview
          default: true

      - name: Install grcov
        run: curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-x86_64-unknown-linux-gnu.tar.bz2 | tar jxf -

      - name: Generate code coverage
        env:
          RUSTFLAGS: -Cinstrument-coverage
          RUSTDOCFLAGS: -Cinstrument-coverage -Zunstable-options --persist-doctests target/debug/doctestbins
          LLVM_PROFILE_FILE: ${{ inputs.profile_file_name_prefix }}-%p-%m.profraw
        run: |
          cargo +nightly test --verbose --all --all-targets ${{ inputs.features_flag }}
          cargo +nightly test --verbose --all --doc ${{ inputs.features_flag }}

      - name: parse code coverage
        run: ./grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info

      - name: Upload to codecov.io
        run: bash <(curl -s https://codecov.io/bash) -f lcov.info
