name: Rust

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Install Rust stable toolchain
      uses: actions-rs/toolchain@v1
      with:
       toolchain: stable
    
    - name: Build with serd
      run: cargo build --verbose --features serde-serialize
      
    - name: Run tests with serd
      run: cargo test --verbose --features serde-serialize
    
    - name: Build no features
      run: cargo build --verbose --no-default-features
      
    - name: Run tests no features
      run: cargo test --verbose --no-default-features
    
    - name: Build simulation bin
      run: cargo build -p simulation-bin
