name: Rust-Beta

on:
  push:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-beta:
    name: rust beta check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: [test, release]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust beta toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: beta
        default: true

    - name: Run tests beta with serd
      run: cargo +beta test --profile ${{ matrix.profile }} --all --verbose --no-fail-fast --features="serde-serialize"
    - name: Run example tests beta with serd
      run: cargo +beta test --profile ${{ matrix.profile }} --all --verbose --no-fail-fast --features="serde-serialize" --examples

    - name: Run tests beta without serd
      run: cargo +beta test --profile ${{ matrix.profile }} --all --verbose --no-fail-fast --no-default-features --features="overflow-test"
    - name: Run example tests beta without serd
      run: cargo +beta test --profile ${{ matrix.profile }} --all --verbose --no-fail-fast --no-default-features --features="overflow-test" --examples
