name: Rust doc check

on:
  workflow_call:
    inputs:
      toolchain:
        description: 'rust toolchain'
        required: false
        type: string
        # options:
        # - stable
        # - nightly
        # - beta
      check_private_items:
        description: 'wether to check documentation for private item'
        required: false
        default: true
        type: boolean

env:
  CARGO_TERM_COLOR: always

jobs:
  rustdoc-check:
    name: Rust Doc check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install Rust stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ inputs.toolchain }}
        components: rust-docs, cargo
        default: true
    
    - name: Doc check
      if: ${{ inputs.check_private_items }}
      run: cargo doc --verbose --all --no-deps --document-private-items --all-features

    - name: Doc check
      if: ${{ !inputs.check_private_items }}
      run: cargo doc --verbose --all --no-deps --all-features
