name: Rust Doc check

on:
  push:
  pull_request:
    branches: [ main, develop ]
    
env:
  CARGO_TERM_COLOR: always

jobs:
  rustdoc-check:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install Rust stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
    
    - name: Doc
      run: cargo +stable doc --all --no-deps --document-private-items --all-features
