name: Rust-Beta

on:
  push:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-beta:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Install Rust beta toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: beta
    
    - name: Build beta
      run: cargo build --verbose
      
    - name: Run tests beta
      run: cargo test --verbose
